### ISSUE TITLE
iPhone 7 problem

### ISSUE THREAD

**Issue by JDiDev** [MrMatthias/SwiftColorPicker#17] opened 2017-03-21 07:08 UTC
This works well on previous devices, but on iPhone 7/plus the color picker image remains unchanged. I guess it has something to do with iPhone 7 having a wider color spectrum (extended rgb) than what was before.

![iphone7](https://cloud.githubusercontent.com/assets/26564892/24135841/b182f00c-0e14-11e7-92f3-7ec1efc066ee.png)

**Comment by aChase55** [comment] 2017-03-28 05:49
Seeing the same issue.  I've noticed this only happens with a physical device.  Color picker renders properly on iPhone 7 simulator

**Comment by sarperdag** [comment] 2017-04-01 13:37
Having the same problem. Anyone found a solution yet?

**Comment by aChase55** [comment] 2017-05-02 04:43
@MrMatthias can you at least try to point me in the right direction with this issue? Or update the status? This is a blocker for any production iOS 10 application.

**Comment by sixpolys** [comment] 2017-05-16 19:24
@aChase55 @sarperdag @JDiDev Can you set the colorspace in PickerImage::createImageFromData like this and see if it fixes the problem:
`let colorSpace = CGColorSpace.init(name: CGColorSpace.sRGB)! `
I don't have a device to test it

**Comment by sarperdag** [comment] 2017-05-16 19:50
already tried it and it's not working...

**Comment by aChase55** [comment] 2017-05-18 05:35
I tried to quickload view the img variable in `ColorPicker`'s drawRect method and got this

```
[Example] ImageIO: handle_error:350: zlib error
[Example] ImageIO: handle_error:350: No IDATs 
```
Looking into it

**Comment by aChase55** [comment] 2017-05-18 06:04
I think it might be a threading issue.  The A10 processor in the iPhone7 devices could be causing a race condition when rendering `ColorPickerImage` 

This would also explain why the issue is only occuring on physical iPhone 7 devices

**Comment by sixpolys** [comment] 2017-06-04 20:58
@aChase55 can you try to disable the changeSize method in PickerImage? Locking should be coordinated in the ColorPicker class which is not the case.

**Comment by aChase55** [comment] 2017-06-06 07:56
@MrMatthias 

Made the following changes:

![screen shot 2017-06-06 at 12 57 19 am](https://cloud.githubusercontent.com/assets/1834258/26819314/2b59421c-4a53-11e7-960b-d6c85603678a.png)

![screen shot 2017-06-06 at 12 51 29 am](https://cloud.githubusercontent.com/assets/1834258/26819170/93fae83a-4a52-11e7-9089-23ff60e17c4c.png)

Still seeing the same:
![screen shot 2017-06-06 at 12 55 56 am](https://cloud.githubusercontent.com/assets/1834258/26819263/f59ed7f4-4a52-11e7-877e-3fe3cecd8c0d.png)

**Comment by bworby** [comment] 2017-06-29 03:51
I just ran into this issue as well. iPhone 7 does not show the Color Picker. Did anyone find a fix for this?

**Comment by h36ahmed** [comment] 2017-08-22 19:19
Hi all, I am running into the same issue. Did someone find a solution?

**Comment by mobileservice0701** [comment] 2017-08-23 02:29
Hi All, this issue is happened on iPhone 7 device only.
did someone resolve this issue?

**Comment by matrejek** [comment] 2017-10-20 06:02
@MrMatthias - I see that it does not affect BinaryClock app - any more ideas?

**Comment by matrejek** [comment] 2017-10-20 08:04
For those looking for the solution - here is the working one https://github.com/FlorianCP/SwiftColorPicker/commit/058ed68311eb7210ff13f0d191a478afa9f50c84

**Comment by matrejek** [comment] 2017-12-09 21:03
I have ported the solution for example branch, will do for master as well.

**Closed as completed** 2018-06-14 07:09 UTC
